### PR TITLE
Add Link header to BoundedLimitOffsetPagination

### LINKED ISSUE #21: Add HTTP link headers to BoundedLimitOffsetPagination
Possibly useful resources:
* https://tools.ietf.org/html/rfc8288
* https://github.com/tbeadle/django-rest-framework-link-header-pagination/blob/master/drf_link_header_pagination/__init__.py
* https://docs.github.com/en/free-pro-team@latest/rest/guides/traversing-with-pagination
* https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination
* https://requests.readthedocs.io/en/master/user/advanced/#link-headers
* https://github.com/psf/requests/blob/c2b307dbefe21177af03f9feb37181a89a799fcc/requests/utils.py#L829

### PR DESCRIPTION
**Pull request by danlamanna**
Fixes #21

### CODE REVIEW

**Comment by brianhelba** [comment]
@danlamanna Per our offline discussion, I refactored this to call the superclass method. PTAL.

**Comment by danlamanna** [comment]
LGTM

**Review by brianhelba — APPROVED** [review]

**Comment by danlamanna** [comment]
In memoriam: https://github.com/girder/girder/pull/2105.

**Comment by mgrauer** [comment]
Jun 15, 2017 to Jan 14, 2021. 

🧟

**Pull request merged**
